### ISSUE TITLE
openshift_service_catalog is failed at openshift-ansible

### ISSUE THREAD

**Issue by s1061123** [redhat-nfvpe/base-infra-bootstrap#29]
I met the following failure in openshift-ansible based on `inventory/example_openshift-ansible/vanilla.inventory` file.

Condition:
- CentOS
- Virtual install

Failure logs:
```
# ansible-playbook -i ./inventory/test1 playbooks/deploy_cluster.yml
(snip)
TASK [openshift_master : Ensure that Template Service Broker has nodes to run on] *********************************
Friday 02 March 2018  06:53:29 -0500 (0:00:00.526)       0:05:51.353 **********
fatal: [openshift-master]: FAILED! => {"msg": "Unexpected templating type error occurred on ({{  __schedulable_nodes_matching_selector['results']['results'][0]['items'] | default([]) | length != 0 }}): object of type 'builtin_function_or_method' has no len()"}
```

Adding following config in inventory, `playbooks/deploy_cluster.yml` works fine.
```
openshift_enable_service_catalog=false
template_service_broker_install=false
```

Did you see such issue?
or how about to add above config in our `inventory/example_openshift-ansible/vanilla.inventory`?

**Comment by leifmadsen** [comment]
I was able to get these working with the 3.9 deployment and containerization methods that Doug had outlined. However, I was having an issue with the ASB on that deployment.

Which version were you using?

**Comment by s1061123** [comment]
I use [https://github.com/redhat-nfvpe/base-infra-bootstrap/blob/master/inventory/example_openshift-ansible/vanilla.inventory](https://github.com/redhat-nfvpe/base-infra-bootstrap/blob/master/inventory/example_openshift-ansible/vanilla.inventory), so version is not selected.
As far as I checked, 3.7 is used for now.

**Comment by s1061123** [comment]
As @leifmadsen , I also see it works in atomic deploy (centos atomic with `inventory/example_openshift-ansible/atomic.inventory`).

I will try to find why...

**Comment by leifmadsen** [comment]
Yea I know @dougbtv was having some issues with deployments of OpenShift on CentOS as well, and I think just switched to using Atomic mostly?

**Comment by dougbtv** [comment]
Spot on, need atomic if you're using `containerized: true` and want
something > 3.7.0

**Comment by s1061123** [comment]
@dougbtv @leifmadsen , thank you for your info!
well, we may need to write somewhere (like README.md) otherwise everyone may try and fail....

**Comment by leifmadsen** [comment]
Good call. I'll do that.
